### ISSUE TITLE
Ифы плохо работают

### ISSUE THREAD

**Issue by vladloh** [GassaFM/interpr#15]
Такой код запускается:
```
function sum (id, pr, n, a):
    q := 0
    if 1:
        if 2:
            q := 1
        egor := 0
    else:
        q := 2
```
Такой не запускается:
```
function sum (id, pr, n, a):
    q := 0
    if 1:
        if 2:
            q := 1
    else:
        q := 2
```
Ошибка:
```
line 7: no added indent for a block
        q := 2
shell returned 1  
```

Тут видно, что есть баг в.обработке вложенных `if-else`: первый код отличается от второго наличием строчки `egor := 0` перед 'else'

**Comment by GassaFM** [comment]
Скорее всего, в последних строках спутаны табы и пробелы.
Таб в отступе не равен никакому количеству пробелов.
Сообщение об этой ошибке [уже улучшено](https://github.com/GassaFM/interpr/commit/74495d76) в мастер-версии.

**Comment by vladloh** [comment]
Нет, это не так, проблема не в табах и пробелах 😡😡😡
