### ISSUE TITLE
Default values of undeclared arrays

### ISSUE THREAD

**Issue by eakravchenko** [GassaFM/interpr#17]
I tried to run program:

function qw (id, pr, n, a):
    l := id * n / pr 
    r := (id + 1) * n / pr
    num := 0
    kek := 0
    for i := l until r:
        if num == 0:
            kek := a[i]
            num += 1
        else:
            if x[i] == kek:
                num += 1
            else:
                num -= 1

    send(0, kek, num)

and it ran. I used undeclared array x without initialization. It means, that undeclared arrays contains default values. What are these values?

**Comment by GassaFM** [comment]
It runs correctly, but only when the line with `x[i]` is not executed.
Try a larger input, or different values of `l` and `r`.
