### ISSUE TITLE
Can't assign array to array

### ISSUE THREAD

**Issue by eakravchenko** [GassaFM/interpr#19]
You can't write 
q := array(d)
w := array(d)
...
w := q

Instead of this you have to write 
q := array(d)
w := array(d)
...
for i := 0 until d:
    w[i] := q[i]

It is very uncomfortable/

**Comment by GassaFM** [comment]
It's fine that there is no `w := q` operation, at least for better readability.
Currently, all operations have an important property: the number of steps is proportional to the number of tokens in the expression (excluding round brackets and commas).
With array assignment, that sure wouldn't be the case.
