### ISSUE TITLE
Непонятное количество тактов для for/while

### ISSUE THREAD

**Issue by petsernik** [GassaFM/interpr#30]
Выполним какую-нибудь простую операцию, например, `x:=0` с помощью цикла несколько раз, посмотрим сколько тактов выводит при этом программа с помощью команды `interpr -d program.pr` со случайными входными данными. По идее оба представленных ниже кода должны выполняться за 9e4 такта (`i:=0; i<1e4; x:=0; i+=1; i<1e4; x:=0; i+=1;...`), а выполняются за 12e4. Получается, что в каждой итерации цикла 3 каких-то лишних такта учитываются. Почему так? 
![image](https://user-images.githubusercontent.com/69345823/111863472-d81a2f00-896c-11eb-816f-65eca7328e41.png)
a.pr
```
function sum (id, pr, n, a):
	for i:=0 until 10000:
		x:=0
```
b.pr
```
function sum (id, pr, n, a):
    i:=0
    while i<10000:
        x:=0
        i+=1
```

**Comment by petsernik** [comment]
Добавил строчку, которая соответствует трём тактам, в цикл с 1e4 итерациями, а выполнение цикла увеличилось на 4e4 такта, что тоже кажется подозрительным 
![image](https://user-images.githubusercontent.com/69345823/111864683-83c67d80-8973-11eb-9078-751856acc9fe.png)

**Comment by petsernik** [comment]
Мой вывод получился такой, `x:=0` (в общем виде `<var> <assignOp> <var>`) выполняется за 4 такта (что отвечает на все мои предыдущие вопросы), вот примеры тестов, которые я делал:
здесь 10 присваиваний:
![image](https://user-images.githubusercontent.com/69345823/111865989-48c84800-897b-11eb-928b-b0b7064ba0ec.png)
а вот здесь уже 100:
![image](https://user-images.githubusercontent.com/69345823/111866239-21727a80-897d-11eb-9cdd-854923f0d82a.png)

**Comment by GassaFM** [comment]
Действительно, разобрались в чате и выяснили, что каждая строка выполняется на один такт больше, чем стоимость в тактах, написанная в `interpr -d`. (Кроме фора, который вообще особый случай.)

Теперь вопрос: как предлагается это исправить и почему?

**Comment by GassaFM** [comment]
Продолжение в #32.
