### ISSUE TITLE
The installation instruction for macOS is invalid for M1-based devices

### ISSUE THREAD

**Issue by ghost** [GassaFM/interpr#37]
Homebrew's dmd package requires x86_64 architecture, while M1 is ARM.
Solution: instead of Homebrew's dmd, interpr should be compiled with [this](https://github.com/ldc-developers/ldc/releases/download/v1.29.0-beta1/ldc2-1.29.0-beta1-osx-arm64.tar.xz).

**Comment by landgrafhomyak** [comment]
+1
