### ISSUE TITLE
Terrible typo

### ISSUE THREAD

**Issue by MaximilianYan** [GassaFM/interpr#46]
There is a terrible mix of spaces between tabs in the *609 line* in *runner.d*:
https://github.com/GassaFM/interpr/blob/b959bb78709345d001a87756532ba8de1c061944/source/runner.d#L608-L610
the last tab before the `evalExpression` is replaced with four spaces!

**Comment by MaximilianYan** [comment]
Such a terrible thing is presented in every place, where the `lvalue =` and `rvalue` are on the different lines. I think that it is not necessary, cause this is not an aligning but only standard offset.

**Comment by GassaFM** [comment]
Block indents are tabs (which can be shown as 4 or 8 or other number of spaces).
Multi-line indents are 4 spaces after tabs.

It may challenge one's sense of beauty, agreed.
However, at least it's consistent, which is an important thing with any given style.
