### ISSUE TITLE
Ошибка при компиляции с помощью gdc

### ISSUE THREAD

**Issue by eqimd** [GassaFM/interpr#5]
При попытке компилирования с помощью gdc выдаёт ошибку, в то время как dmd всё компилирует.
Команда:
```
gdc interpr.d language.d parser.d runner.d display.d
```
Ошибка:
```javascript
runner.d:66:10: error: basic type expected, not foreach
   static foreach (cur; args)
          ^
runner.d:66:10: error: no identifier for declarator _error_
   static foreach (cur; args)
```

**Comment by GassaFM** [comment]
В этом месте вызывается функция с произвольным набором аргументов, и static foreach разбирает их на этапе компиляции.

[Видимо](https://forum.dlang.org/thread/xxiymhwycakkanyfytxm@forum.dlang.org), в gdc тяжело со static foreach. А в самом языке эта конструкция есть с версии 2.077 (ноябрь 2017). Можно использовать другие компиляторы &mdash; dmd или ldc &mdash; или собрать современную версию gdc из исходников.

Поскольку удалось собрать с dmd, этот issue я закрываю.
